#!/usr/bin/env node
/**
 * @project AncestorTree
 * @file scripts/local-setup.mjs
 * @description Cross-platform local development setup script.
 *              Starts Supabase CLI (Docker) and writes .env.local automatically.
 * @version 1.0.0
 * @updated 2026-02-26
 */

import { execSync, spawnSync } from 'node:child_process'
import { existsSync, writeFileSync, readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')          // frontend/
const ENV_FILE = resolve(ROOT, '.env.local')

const GREEN  = '\x1b[32m'
const YELLOW = '\x1b[33m'
const RED    = '\x1b[31m'
const CYAN   = '\x1b[36m'
const RESET  = '\x1b[0m'

const ok   = (msg) => console.log(`${GREEN}✅ ${msg}${RESET}`)
const warn = (msg) => console.log(`${YELLOW}⚠️  ${msg}${RESET}`)
const err  = (msg) => console.error(`${RED}❌ ${msg}${RESET}`)
const info = (msg) => console.log(`${CYAN}ℹ  ${msg}${RESET}`)
const step = (msg) => console.log(`\n${CYAN}▶ ${msg}${RESET}`)

// ─── 1. Check prerequisites ───────────────────────────────────────────────

step('Checking prerequisites...')

// Docker
const docker = spawnSync('docker', ['info'], { stdio: 'pipe' })
if (docker.status !== 0) {
  err('Docker Desktop is not running.')
  info('  → Download: https://www.docker.com/products/docker-desktop')
  info('  → Start Docker Desktop, then run this script again.')
  process.exit(1)
}
ok('Docker is running')

// Supabase CLI
const sbVersion = spawnSync('supabase', ['--version'], { stdio: 'pipe' })
if (sbVersion.status !== 0) {
  err('Supabase CLI not found.')
  info('  → Install: brew install supabase/tap/supabase  (macOS/Linux)')
  info('  → Install: scoop install supabase              (Windows)')
  info('  → Or: npm install -g supabase')
  process.exit(1)
}
ok(`Supabase CLI found: ${sbVersion.stdout.toString().trim()}`)

// Node.js version
const nodeMajor = parseInt(process.versions.node.split('.')[0], 10)
if (nodeMajor < 18) {
  err(`Node.js 18+ required (found ${process.versions.node})`)
  process.exit(1)
}
ok(`Node.js ${process.versions.node}`)

// ─── 2. Start Supabase local stack ───────────────────────────────────────

step('Starting Supabase local stack (this may take a moment on first run)...')
info('  Ports: API=54321 | DB=54322 | Studio=54323')

try {
  execSync('supabase start', { cwd: ROOT, stdio: 'inherit' })
} catch {
  // `supabase start` exits non-zero when already running — check status
  const check = spawnSync('supabase', ['status'], { cwd: ROOT, stdio: 'pipe' })
  if (check.status !== 0) {
    err('Failed to start Supabase. Check Docker logs.')
    process.exit(1)
  }
  warn('Supabase was already running — using existing instance.')
}

ok('Supabase local stack is running')

// ─── 3. Parse `supabase status` output ───────────────────────────────────

step('Reading local credentials from supabase status...')

const statusResult = spawnSync('supabase', ['status'], { cwd: ROOT, stdio: 'pipe' })
if (statusResult.status !== 0) {
  err('Could not read supabase status. Is Docker running?')
  process.exit(1)
}

const statusText = statusResult.stdout.toString()

function extractValue(text, key) {
  const match = text.match(new RegExp(`${key}:\\s*(.+)`))
  return match ? match[1].trim() : null
}

const apiUrl      = extractValue(statusText, 'API URL')
const anonKey     = extractValue(statusText, 'anon key')
const serviceKey  = extractValue(statusText, 'service_role key')

if (!apiUrl || !anonKey) {
  err('Could not parse supabase status output.')
  console.log(statusText)
  process.exit(1)
}

ok(`API URL:  ${apiUrl}`)
ok(`Anon key: ${anonKey.slice(0, 20)}...`)

// ─── 4. Write .env.local ─────────────────────────────────────────────────

step('Writing .env.local...')

const envContent = `# ⚠️  LOCAL DEVELOPMENT — auto-generated by scripts/local-setup.mjs
# DO NOT commit this file. Run 'pnpm local:setup' to regenerate.

# Supabase local instance
NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
${serviceKey ? `SUPABASE_SERVICE_ROLE_KEY=${serviceKey}` : '# SUPABASE_SERVICE_ROLE_KEY=<service_role key from supabase status>'}

# Local development flag
NEXT_PUBLIC_LOCAL_DEV=true
`

const existed = existsSync(ENV_FILE)
if (existed) {
  // Back up existing .env.local if it contains a cloud URL
  const existing = readFileSync(ENV_FILE, 'utf-8')
  if (existing.includes('supabase.co')) {
    const backup = ENV_FILE + '.cloud.bak'
    writeFileSync(backup, existing)
    warn(`.env.local pointed to cloud — backed up to .env.local.cloud.bak`)
  }
}

writeFileSync(ENV_FILE, envContent, 'utf-8')
ok(`.env.local ${existed ? 'updated' : 'created'}`)

// ─── 5. Done ─────────────────────────────────────────────────────────────

console.log(`
${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  🎉 Local stack is ready!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

  App:          ${CYAN}pnpm dev${RESET}  →  http://localhost:4000
  Supabase UI:  http://localhost:54323
  DB direct:    postgresql://postgres:postgres@localhost:54322/postgres

  Demo accounts:
    admin@giapha.local  /  admin123
    viewer@giapha.local /  viewer123

  Commands:
    ${CYAN}pnpm local:start${RESET}  — start containers (after first setup)
    ${CYAN}pnpm local:stop${RESET}   — stop containers (keep data)
    ${CYAN}pnpm local:reset${RESET}  — reset DB + re-seed demo data
    ${CYAN}pnpm local:setup${RESET}  — full setup (this script)
`)
